"""Tests for CLI module."""

from pathlib import Path
from unittest.mock import MagicMock, patch
from rich.console import Console
from typer.testing import CliRunner

from teich.cli import BatchProgressReporter, app
from teich.runner import SessionProgressUpdate, TraceMetrics

runner = CliRunner()


def test_init_command(tmp_path: Path):
    """Test init command creates files."""
    result = runner.invoke(app, ["init", str(tmp_path)])

    assert result.exit_code == 0
    assert "Created" in result.output

    # Check files were created
    assert (tmp_path / "config.yaml").exists()
    assert (tmp_path / "prompts.csv").exists()


def test_init_command_existing_files(tmp_path: Path):
    """Test init command handles existing files."""
    # Create existing file
    (tmp_path / "config.yaml").write_text("existing")

    result = runner.invoke(app, ["init", str(tmp_path)])

    assert result.exit_code == 0
    assert "Already exists" in result.output


def test_generate_command_missing_config():
    """Test generate command fails with missing config."""
    result = runner.invoke(app, ["generate", "-c", "/nonexistent/config.yaml"])

    assert result.exit_code == 1
    assert "not found" in result.output


def test_generate_command_no_prompts(tmp_path: Path):
    """Test generate command fails when no prompts configured."""
    config_file = tmp_path / "config.yaml"
    config_file.write_text("""
model:
  model: codex-mini-latest
prompts: []
""")

    result = runner.invoke(app, ["generate", "-c", str(config_file)])

    assert result.exit_code == 1
    assert "No prompts configured" in result.output


def test_generate_command_success_codex(tmp_path: Path):
    """Test generate command runs successfully with codex provider."""
    config_file = tmp_path / "config.yaml"
    config_file.write_text(f"""
agent:
  provider: codex
model:
  model: codex-mini-latest
prompts:
  - Build a todo app
output:
  traces_dir: {tmp_path}/output
openai_api_key: sk-test
""")

    with patch('teich.cli.CodexRunner') as mock_runner:
        mock_instance = MagicMock()
        mock_instance.run_all.return_value = [tmp_path / "output/session1.jsonl"]
        mock_runner.return_value = mock_instance

        output_dir = tmp_path / "output"
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "session1.jsonl").write_text(
            '{"type":"session_meta","payload":{"id":"session1","base_instructions":{"text":"You are a coding agent.\\n\\nAvailable tools:\\n- bash: Run shell commands\\n"}}}\n'
            '{"type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"Build a todo app"}]}}\n'
            '{"type":"response_item","payload":{"type":"function_call","name":"bash","call_id":"call_1","arguments":"{\\"command\\":\\"ls\\"}"}}\n'
        )

        result = runner.invoke(app, ["generate", "-c", str(config_file)])

        assert result.exit_code == 0
        assert "Success" in result.output
        assert "Generated 1 trace files" in result.output
        assert "tokens=" in result.output
        assert "api_tokens=" not in result.output
        assert "est_total_tokens=" not in result.output
        assert (output_dir / "README.md").exists()
        readme = (output_dir / "README.md").read_text(encoding="utf-8")
        assert "All assistant responses were generated by **codex-mini-latest**." in readme
        assert "## Training-ready tools" in readme
        assert '"name": "bash"' in readme
        assert '"description": "Run shell commands"' in readme
        assert '"command"' in readme


def test_batch_progress_reporter_only_shows_queued_and_running_rows():
    console = Console(record=True, width=160)
    reporter = BatchProgressReporter(console)

    reporter.update(
        SessionProgressUpdate(
            prompt_id="queued-1",
            prompt_index=1,
            total_prompts=3,
            prompt="Queued prompt",
            prompt_preview="Queued prompt",
            status="queued",
        )
    )
    reporter.update(
        SessionProgressUpdate(
            prompt_id="running-1",
            prompt_index=2,
            total_prompts=3,
            prompt="Running prompt",
            prompt_preview="Running prompt",
            status="running",
            metrics=TraceMetrics(total_tokens=42, total_cost=0.125, model="codex-mini-latest"),
        )
    )
    reporter.update(
        SessionProgressUpdate(
            prompt_id="completed-1",
            prompt_index=3,
            total_prompts=3,
            prompt="Completed prompt",
            prompt_preview="Completed prompt",
            status="completed",
            metrics=TraceMetrics(total_tokens=99, total_cost=0.5, model="codex-mini-latest"),
        )
    )

    console.print(reporter._render())
    output = console.export_text()

    assert "queued=1 running=1 completed=1 failed=0" in output
    assert "tokens=141" in output
    assert "Queued prompt" in output
    assert "Running prompt" in output
    assert "Completed prompt" not in output
    assert "api tokens" not in output
    assert "est. total" not in output
