import json
from pathlib import Path

from teich.trace_readme import build_traces_readme, write_traces_readme


def test_build_traces_readme_includes_model_and_references_tools(tmp_path: Path):
    trace_file = tmp_path / "trace.jsonl"
    trace_file.write_text(
        '{"type":"session_meta","payload":{"id":"session1"}}\n'
        '{"type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"Build a todo app"}]}}\n'
        '{"type":"response_item","payload":{"type":"tool_schema","name":"bash","schema":{"description":"Run shell commands","parameters":{"type":"object","properties":{"command":{"type":"string"}},"required":["command"],"additionalProperties":false}}}}\n'
        '{"type":"response_item","payload":{"type":"function_call","name":"bash","call_id":"call_1","arguments":"{\\"command\\":\\"ls\\"}"}}\n',
        encoding="utf-8",
    )

    readme = build_traces_readme(
        pretty_name="Agentic Training Traces",
        trace_files=[trace_file],
        tags=["agent-traces", "codex"],
        model_id="codex-mini-latest",
    )

    assert "This dataset was generated using [teich](https://github.com/TeichAI/teich) by [TeichAI](https://huggingface.co/TeichAI)" in readme
    assert 'tags:' in readme
    assert '- "agent-traces"' in readme
    assert '- "codex"' in readme
    assert "Load, format, and mask these datasets for supervised fine-tuning" in readme
    assert "All assistant responses were generated by **codex-mini-latest**." in readme
    assert "## Training-ready tools" in readme
    assert "tools.json" in readme
    assert '"name": "bash"' not in readme
    assert "## Conversion" in readme
    assert "load_traces" in readme
    assert "format_and_mask" in readme
    assert "tokenizer.apply_chat_template" in readme
    assert "tools=example.get('tools') or []" in readme
    assert "convert_traces_to_training_data" not in readme


def test_write_traces_readme_creates_tools_json(tmp_path: Path):
    trace_file = tmp_path / "trace.jsonl"
    trace_file.write_text(
        '{"type":"session_meta","payload":{"id":"session1"}}\n'
        '{"type":"response_item","payload":{"type":"tool_schema","name":"bash","schema":{"description":"Run shell commands","parameters":{"type":"object","properties":{"command":{"type":"string"}},"required":["command"],"additionalProperties":false}}}}\n'
        '{"type":"response_item","payload":{"type":"function_call","name":"bash","call_id":"call_1","arguments":"{\\"command\\":\\"ls\\"}"}}\n',
        encoding="utf-8",
    )

    readme_path = write_traces_readme(
        tmp_path,
        pretty_name="Agentic Training Traces",
        tags=["agent-traces"],
        model_id="test-model",
    )

    assert readme_path.exists()
    tools_path = tmp_path / "tools.json"
    assert tools_path.exists()

    tools = json.loads(tools_path.read_text(encoding="utf-8"))
    assert len(tools) == 1
    assert tools[0]["function"]["name"] == "bash"
    assert tools[0]["function"]["description"] == "Run shell commands"
    assert tools[0]["function"]["parameters"]["additionalProperties"] is False


def test_write_traces_readme_for_structured_chat_dataset_skips_tools_json(tmp_path: Path):
    trace_file = tmp_path / "chat.jsonl"
    trace_file.write_text(
        '{"messages":[{"role":"system","content":"You are a helpful assistant","thinking":null},{"role":"user","content":"Hello","thinking":null},{"role":"assistant","content":"Hi!","thinking":"I should greet the user."}],"system":"You are a helpful assistant","prompt":"Hello","thinking":"I should greet the user.","response":"Hi!","model":"gpt-4.1-mini"}\n',
        encoding="utf-8",
    )

    readme_path = write_traces_readme(
        tmp_path,
        pretty_name="Chat Dataset",
        tags=["chat"],
        model_id="gpt-4.1-mini",
    )

    readme = readme_path.read_text(encoding="utf-8")
    assert '- "chat"' in readme
    assert "newline-delimited JSON training examples generated by teich" in readme
    assert "Chat-only datasets include `messages` plus convenience fields like `system`, `prompt`, `thinking`, and `response`." in readme
    assert "## Training-ready tools" not in readme
    assert not (tmp_path / "tools.json").exists()
